# Generated by Django 5.1.7 on 2025-05-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_interaction_user_id_alter_interaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='user_id',
            new_name='usr',
        ),
    ]
